version: '3'
services:

  fe01:
    image: harryhan1989/starrokcs:2.2.0-rc01
    container_name: fe01
    hostname: fe01
    restart: always
    command: ["fe"]
    environment:
      FE_HOST: 172.16.238.21
      FE_TYPE: follower
      FE_NETWORK: 172.16.238.0/24
    volumes:
      - /root/data/db/starrocks/fe01/log:/opt/StarRocks-2.2.0-rc01/fe/log:rw
      - /root/data/db/starrocks/fe01/starrocks-meta:/opt/StarRocks-2.2.0-rc01/fe/starrocks-meta:rw
      - /root/data/db/starrocks/fe01/temp_dir:/opt/StarRocks-2.2.0-rc01/fe/temp_dir:rw
    ports:
      - "8030:8030"
      - "9030:9030"
    networks:
      app_net:
        ipv4_address: 172.16.238.21

  fe02:
    image: harryhan1989/starrokcs:2.2.0-rc01
    container_name: fe02
    hostname: fe02
    restart: always
    command: ["fe"]
    depends_on:
      - fe01
    environment:
      MASTER_FE_HOST: 172.16.238.21
      FE_HOST: 172.16.238.22
      FE_TYPE: follower
      FE_NETWORK: 172.16.238.0/24
    volumes:
      - /root/data/db1/starrocks/fe02/log:/opt/StarRocks-2.2.0-rc01/fe/log:rw
      - /root/data/db1/starrocks/fe02/starrocks-meta:/opt/StarRocks-2.2.0-rc01/fe/starrocks-meta:rw
      - /root/data/db1/starrocks/fe02/temp_dir:/opt/StarRocks-2.2.0-rc01/fe/temp_dir:rw
    ports:
      - "8031:8030"
      - "9031:9030"
    networks:
      app_net:
        ipv4_address: 172.16.238.22

  fe03:
    image: harryhan1989/starrokcs:2.2.0-rc01
    container_name: fe03
    hostname: fe03
    restart: always
    command: ["fe"]
    depends_on:
      - fe01
    environment:
      MASTER_FE_HOST: 172.16.238.21
      FE_HOST: 172.16.238.23
      FE_TYPE: follower
      FE_NETWORK: 172.16.238.0/24
    volumes:
      - /root/data/db2/starrocks/fe03/log:/opt/StarRocks-2.2.0-rc01/fe/log:rw
      - /root/data/db2/starrocks/fe03/starrocks-meta:/opt/StarRocks-2.2.0-rc01/fe/starrocks-meta:rw
      - /root/data/db2/starrocks/fe03/temp_dir:/opt/StarRocks-2.2.0-rc01/fe/temp_dir:rw
    networks:
      app_net:
        ipv4_address: 172.16.238.23

  be01:
    image: harryhan1989/starrokcs:2.2.0-rc01
    container_name: be01
    hostname: be01
    restart: always
    command: [ "be" ]
    depends_on:
      - fe01
    environment:
      FE_HOST: 172.16.238.21
      BE_HOST: 172.16.238.31
      BE_NETWORK: 172.16.238.0/24
    volumes:
      - /root/data/db1/starrocks/be01/log:/opt/StarRocks-2.2.0-rc01/be/log:rw
      - /root/data/db1/starrocks/be01/data:/opt/StarRocks-2.2.0-rc01/be/data:rw
    networks:
      app_net:
        ipv4_address: 172.16.238.31

  be02:
    image: harryhan1989/starrokcs:2.2.0-rc01
    container_name: be02
    hostname: be02
    restart: always
    command: [ "be" ]
    depends_on:
      - fe01
    environment:
      FE_HOST: 172.16.238.21
      BE_HOST: 172.16.238.32
      BE_NETWORK: 172.16.238.0/24
    volumes:
      - /root/data/db1/starrocks/be02/log:/opt/StarRocks-2.2.0-rc01/be/log:rw
      - /root/data/db1/starrocks/be02/data:/opt/StarRocks-2.2.0-rc01/be/data:rw
    networks:
      app_net:
        ipv4_address: 172.16.238.32

  be03:
    image: harryhan1989/starrokcs:2.2.0-rc01
    container_name: be03
    hostname: be03
    restart: always
    command: [ "be" ]
    depends_on:
      - fe01
    environment:
      FE_HOST: 172.16.238.21
      BE_HOST: 172.16.238.33
      BE_NETWORK: 172.16.238.0/24
    volumes:
      - /root/data/db2/starrocks/be03/log:/opt/StarRocks-2.2.0-rc01/be/log:rw
      - /root/data/db2/starrocks/be03/data:/opt/StarRocks-2.2.0-rc01/be/data:rw
    networks:
      app_net:
        ipv4_address: 172.16.238.33
        
networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"